# Generated by Django 5.2.1 on 2025-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_populate_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='times',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
