# Generated by Django 5.2.5 on 2025-08-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_allergentermchangerequest'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL: Fix both sequences to the correct values
            sql="""
            -- Fix the main annotation sequence
            SELECT setval('recipes_annotation_id_seq', COALESCE((SELECT MAX(id) FROM recipes_annotation), 1));
            
            -- Fix the historical annotation sequence
            SELECT setval('recipes_historicalannotation_history_id_seq', COALESCE((SELECT MAX(history_id) FROM recipes_historicalannotation), 1));
            """,
            # Reverse SQL: No reverse operation needed (sequences will continue from current values)
            reverse_sql=""
        ),
    ]
