# Generated by Django 5.2.5 on 2025-08-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_fix_annotation_sequences'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL: Fix all sequences to the correct values (main tables + historical tables)
            sql="""
            -- Function to fix sequence for a given table
            CREATE OR REPLACE FUNCTION fix_sequence(table_name TEXT, sequence_name TEXT)
            RETURNS VOID AS $$
            DECLARE
                max_id BIGINT;
            BEGIN
                -- Get the maximum ID from the table
                EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I', table_name) INTO max_id;
                
                -- Reset the sequence to the correct value
                IF max_id > 0 THEN
                    EXECUTE format('SELECT setval(%L, %s, false)', sequence_name, max_id + 1);
                END IF;
            END;
            $$ LANGUAGE plpgsql;
            
            -- Function to fix historical sequence for a given table
            CREATE OR REPLACE FUNCTION fix_historical_sequence(table_name TEXT, sequence_name TEXT)
            RETURNS VOID AS $$
            DECLARE
                max_history_id BIGINT;
            BEGIN
                -- Get the maximum history_id from the historical table
                EXECUTE format('SELECT COALESCE(MAX(history_id), 0) FROM %I', table_name) INTO max_history_id;
                
                -- Reset the sequence to the correct value
                IF max_history_id > 0 THEN
                    EXECUTE format('SELECT setval(%L, %s, false)', sequence_name, max_history_id + 1);
                END IF;
            END;
            $$ LANGUAGE plpgsql;
            
            -- Fix sequences for all main recipe tables that have data
            SELECT fix_sequence('recipes_annotation', 'recipes_annotation_id_seq');
            SELECT fix_sequence('recipes_recipefeedback', 'recipes_recipefeedback_id_seq');
            SELECT fix_sequence('recipes_userfeedback', 'recipes_userfeedback_id_seq');
            SELECT fix_sequence('recipes_feedbackanalytics', 'recipes_feedbackanalytics_id_seq');
            SELECT fix_sequence('recipes_feedbackexport', 'recipes_feedbackexport_id_seq');
            SELECT fix_sequence('recipes_feedbacktemplate', 'recipes_feedbacktemplate_id_seq');
            SELECT fix_sequence('recipes_feedbackresponse', 'recipes_feedbackresponse_id_seq');
            SELECT fix_sequence('recipes_feedbackimpact', 'recipes_feedbackimpact_id_seq');
            SELECT fix_sequence('recipes_feedbackbatch', 'recipes_feedbackbatch_id_seq');
            SELECT fix_sequence('recipes_allergentermchangerequest', 'recipes_allergentermchangerequest_id_seq');
            SELECT fix_sequence('recipes_userprofile', 'recipes_userprofile_id_seq');
            
            -- Fix sequences for all historical recipe tables that have data
            SELECT fix_historical_sequence('recipes_historicalannotation', 'recipes_historicalannotation_history_id_seq');
            SELECT fix_historical_sequence('recipes_historicalrecipefeedback', 'recipes_historicalrecipefeedback_history_id_seq');
            SELECT fix_historical_sequence('recipes_historicalallergencategory', 'recipes_historicalallergencategory_history_id_seq');
            SELECT fix_historical_sequence('recipes_historicalallergensynonym', 'recipes_historicalallergensynonym_history_id_seq');
            SELECT fix_historical_sequence('recipes_historicalingredient', 'recipes_historicalingredient_history_id_seq');
            SELECT fix_historical_sequence('recipes_historicalrecipe', 'recipes_historicalrecipe_history_id_seq');
            
            -- Clean up the helper functions
            DROP FUNCTION fix_sequence(TEXT, TEXT);
            DROP FUNCTION fix_historical_sequence(TEXT, TEXT);
            """,
            # Reverse SQL: No reverse operation needed (sequences will continue from current values)
            reverse_sql=""
        ),
    ]
